baseURL = "https://harakumar.github.io/rickfarmiloe/"
languageCode = "en-us"
theme = "hugograyscale"
title = "Hugo Grayscale Theme"
[[menu.main]]
identifier = "Original"
name = "Original"
url = "http://startbootstrap.com/template-overviews/grayscale/"
weight = 1
[params]
author = "RunningStream"
description = "A port of the Grayscale theme to Hugo"
